# Generated by Django 5.2.8 on 2025-11-23 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s]{7,20}$', 'Invalid phone number')])),
                ('address', models.TextField(blank=True)),
                ('customer_type', models.CharField(blank=True, db_index=True, default='', help_text='Customer type managed by frontend (e.g., Bandwidth, MAC, SOHO)', max_length=50)),
                ('link_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('customer_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated customer number: KTL-{8 chars customer name}-{customer id}', max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lost', 'Lost')], db_index=True, default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s]{7,20}$', 'Invalid phone number')])),
                ('address', models.TextField(blank=True)),
                ('potential_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, db_index=True, default='', help_text='Status managed by frontend (e.g., new, contacted, qualified, lost)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prospect_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_prospect_attachments',
            },
        ),
        migrations.CreateModel(
            name='ProspectFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_prospect_followups',
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='ProspectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sales_prospect_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
