# Generated by Django 5.2.8 on 2025-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='potential_revenue',
        ),
        migrations.AddField(
            model_name='customer',
            name='link_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
