# Generated by Django 5.2.8 on 2025-11-27 10:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KAMMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kam_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kam_master',
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('company_id', models.CharField(blank=True, help_text='Company reference ', max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s]{7,20}$', 'Invalid phone number')])),
                ('address', models.TextField()),
                ('customer_type', models.CharField(choices=[('bw', 'Bandwidth'), ('channel_partner', 'Channel Partner'), ('soho', 'SOHO/Home')], max_length=20)),
                ('customer_number', models.CharField(max_length=50, unique=True)),
                ('total_client', models.IntegerField(default=0, help_text='MAC only')),
                ('total_active_client', models.IntegerField(default=0, help_text='MAC only')),
                ('previous_total_client', models.IntegerField(default=0, help_text='MAC only')),
                ('free_giveaway_client', models.IntegerField(default=0, help_text='MAC only')),
                ('default_percentage_share', models.DecimalField(decimal_places=2, default=0, help_text='MAC only', max_digits=5)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_bill_invoice_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
                ('kam_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.kammaster')),
            ],
            options={
                'db_table': 'customer_master',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
