# Generated by Django 5.2.8 on 2025-11-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_kammaster_customermaster_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermaster',
            old_name='company_id',
            new_name='company_name',
        ),
    ]
