# Generated by Django 5.2.8 on 2025-11-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_potential_revenue_customer_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='monthly_revenue',
        ),
    ]
