# Generated by Django 5.2.8 on 2025-12-01 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_company_id_customermaster_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Auto-set to current user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Auto-generated', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Auto-set to current user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
