# Generated by Django 5.2.8 on 2025-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_monthly_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lost', 'Lost')], db_index=True, default='Active', max_length=10),
        ),
    ]
