# Generated by Django 5.2.8 on 2025-11-18 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated customer number: KTL-{10 chars of name}-{DDMMYYYY}', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='sales_custo_custome_9ac778_idx'),
        ),
    ]
