# Generated by Django 5.2.8 on 2025-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customermaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='default_percentage_share',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='MAC only', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='free_giveaway_client',
            field=models.IntegerField(blank=True, default=0, help_text='MAC only', null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='previous_total_client',
            field=models.IntegerField(blank=True, default=0, help_text='MAC only', null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='total_active_client',
            field=models.IntegerField(blank=True, default=0, help_text='MAC only', null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='total_client',
            field=models.IntegerField(blank=True, default=0, help_text='MAC only', null=True),
        ),
    ]
