# Generated by Django 5.2.8 on 2025-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_customer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated customer number: KTL-{8 chars customer name}-{customer id}', max_length=50, null=True, unique=True),
        ),
    ]
