# Generated by Django 5.2.8 on 2025-12-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customermaster_default_percentage_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Auto-generated', max_length=50, null=True, unique=True),
        ),
    ]
