# Generated by Django 5.2.8 on 2025-11-20 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_customer_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Bandwidth', 'Bandwidth/Reseller Customer'), ('MAC', 'MAC Partner/Channel Partner/Franchise'), ('SOHO', 'SOHO/Home Customer')], db_index=True, default='Bandwidth', help_text='Type of customer: Bandwidth/Reseller, MAC Partner, or SOHO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'status'], name='sales_custo_custome_3fa613_idx'),
        ),
    ]
