# Generated by Django 5.2.8 on 2025-11-18 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title describing the feedback/requirement', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the feedback or requirement')),
                ('category', models.CharField(choices=[('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('improvement', 'Improvement'), ('ui_ux', 'UI/UX Enhancement'), ('performance', 'Performance'), ('security', 'Security'), ('integration', 'Integration'), ('documentation', 'Documentation'), ('other', 'Other')], default='feature_request', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email (if different from user email)', max_length=254)),
                ('expected_benefit', models.TextField(blank=True, help_text='Expected benefit or impact of this feature/improvement')),
                ('use_case', models.TextField(blank=True, help_text='Specific use case or scenario where this would be helpful')),
                ('current_workaround', models.TextField(blank=True, help_text='Current workaround (if applicable)')),
                ('related_module', models.CharField(blank=True, help_text='Related module/feature (e.g., Customers, Bills, Invoices)', max_length=100)),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (screenshot, document, etc.)', null=True, upload_to='feedback_attachments/')),
                ('vote_count', models.IntegerField(default=0, help_text='Number of upvotes')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_effort', models.CharField(blank=True, help_text='Estimated development effort (e.g., "2 weeks", "1 month")', max_length=50)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for development team (not visible to submitter)')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/Manager who reviewed this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment (only visible to admins/managers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(help_text='Feedback item this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback')),
                ('user', models.ForeignKey(blank=True, help_text='User who posted this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(help_text='Feedback item being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedback')),
                ('user', models.ForeignKey(help_text='User who voted', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_votes',
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='feedback_status_d7fa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category'], name='feedback_categor_2a8dde_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['priority'], name='feedback_priorit_8f0cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['submitted_by'], name='feedback_submitt_713d03_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-vote_count'], name='feedback_vote_co_747dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['feedback'], name='feedback_co_feedbac_18d2df_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['created_at'], name='feedback_co_created_494aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackvote',
            index=models.Index(fields=['feedback', 'user'], name='feedback_vo_feedbac_8becba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackvote',
            unique_together={('feedback', 'user')},
        ),
    ]
