# Generated by Django 5.2.8 on 2025-11-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title describing the feedback/requirement', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the feedback or requirement')),
                ('category', models.CharField(choices=[('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('improvement', 'Improvement'), ('ui_ux', 'UI/UX Enhancement'), ('performance', 'Performance'), ('security', 'Security'), ('integration', 'Integration'), ('documentation', 'Documentation'), ('other', 'Other')], default='feature_request', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email (if different from user email)', max_length=254)),
                ('expected_benefit', models.TextField(blank=True, help_text='Expected benefit or impact of this feature/improvement')),
                ('use_case', models.TextField(blank=True, help_text='Specific use case or scenario where this would be helpful')),
                ('current_workaround', models.TextField(blank=True, help_text='Current workaround (if applicable)')),
                ('related_module', models.CharField(blank=True, help_text='Related module/feature (e.g., Customers, Bills, Invoices)', max_length=100)),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (screenshot, document, etc.)', null=True, upload_to='feedback_attachments/')),
                ('vote_count', models.IntegerField(default=0, help_text='Number of upvotes')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_effort', models.CharField(blank=True, help_text='Estimated development effort (e.g., "2 weeks", "1 month")', max_length=50)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for development team (not visible to submitter)')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment (only visible to admins/managers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_votes',
            },
        ),
    ]
