# Generated by Django 5.2.8 on 2025-11-23 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Manager who reviewed this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackcomment',
            name='feedback',
            field=models.ForeignKey(help_text='Feedback item this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback'),
        ),
        migrations.AddField(
            model_name='feedbackcomment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who posted this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackvote',
            name='feedback',
            field=models.ForeignKey(help_text='Feedback item being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedback'),
        ),
        migrations.AddField(
            model_name='feedbackvote',
            name='user',
            field=models.ForeignKey(help_text='User who voted', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='feedback_status_d7fa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category'], name='feedback_categor_2a8dde_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['priority'], name='feedback_priorit_8f0cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['submitted_by'], name='feedback_submitt_713d03_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-vote_count'], name='feedback_vote_co_747dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['feedback'], name='feedback_co_feedbac_18d2df_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['created_at'], name='feedback_co_created_494aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackvote',
            index=models.Index(fields=['feedback', 'user'], name='feedback_vo_feedbac_8becba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackvote',
            unique_together={('feedback', 'user')},
        ),
    ]
