# Generated by Django 5.2.8 on 2025-11-27 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_kammaster_customermaster_delete_customer'),
        ('package', '0001_initial'),
        ('utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEntitlementMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('nttn_company', models.CharField(blank=True, max_length=200, null=True)),
                ('nttn_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_of_bw', models.CharField(blank=True, help_text='Home only', max_length=50, null=True)),
                ('type_of_connection', models.CharField(blank=True, help_text='Home only', max_length=50, null=True)),
                ('connected_pop', models.CharField(blank=True, help_text='Home only', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entitlements', to=settings.AUTH_USER_MODEL)),
                ('customer_master_id', models.ForeignKey(db_column='customer_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='customers.customermaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_entitlement_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEntitlementDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('bw', 'Bandwidth'), ('channel_partner', 'Channel Partner'), ('soho', 'SOHO/Home')], max_length=20)),
                ('mbps', models.DecimalField(blank=True, decimal_places=2, help_text='Only MAC & BW', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Only MAC & BW - BW bandwidth prices (ipt,gcc,cdn,nix,baishan) stored here', max_digits=12, null=True)),
                ('custom_mac_percentage_share', models.DecimalField(blank=True, decimal_places=2, help_text='MAC only', max_digits=5, null=True)),
                ('last_changes_updated_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entitlement_details', to=settings.AUTH_USER_MODEL)),
                ('package_pricing_id', models.ForeignKey(blank=True, db_column='package_pricing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_details', to='package.packagepricing')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entitlement_details', to=settings.AUTH_USER_MODEL)),
                ('cust_entitlement_id', models.ForeignKey(db_column='cust_entitlement_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bills.customerentitlementmaster')),
            ],
            options={
                'db_table': 'customer_entitlement_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('total_bill_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_balance_due', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, default='draft', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer_entitlement_master_id', models.OneToOneField(db_column='customer_entitlement_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bills.customerentitlementmaster')),
                ('information_master_id', models.ForeignKey(blank=True, db_column='information_master_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='utility.utilityinformationmaster')),
            ],
            options={
                'db_table': 'invoice_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sub_discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('entitlement_details_id', models.ForeignKey(blank=True, db_column='entitlement_details_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='bills.customerentitlementdetails')),
                ('invoice_master_id', models.ForeignKey(db_column='invoice_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bills.invoicemaster')),
            ],
            options={
                'db_table': 'invoice_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
