# Generated by Django 5.2.8 on 2025-11-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='customer',
            field=models.ForeignKey(help_text='Customer for this bill record', on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='dailybillamount',
            name='bill_record',
            field=models.ForeignKey(help_text='The bill record this daily amount belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_amounts', to='bills.billrecord'),
        ),
        migrations.AddIndex(
            model_name='macpartner',
            index=models.Index(fields=['mac_cust_name'], name='mac_partner_mac_cus_bb6c31_idx'),
        ),
        migrations.AddIndex(
            model_name='macpartner',
            index=models.Index(fields=['is_active'], name='mac_partner_is_acti_3a80b2_idx'),
        ),
        migrations.AddIndex(
            model_name='macpartner',
            index=models.Index(fields=['mac_partner_number'], name='mac_partner_mac_par_6c9b03_idx'),
        ),
        migrations.AddField(
            model_name='macendcustomer',
            name='mac_partner',
            field=models.ForeignKey(help_text='MAC partner this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='end_customers', to='bills.macpartner'),
        ),
        migrations.AddField(
            model_name='macbill',
            name='mac_partner',
            field=models.ForeignKey(help_text='MAC partner this bill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bills.macpartner'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['type', 'is_active'], name='packages_type_e704ee_idx'),
        ),
        migrations.AddField(
            model_name='macendcustomer',
            name='package',
            field=models.ForeignKey(help_text='Package assigned to this customer', limit_choices_to={'type': 'MAC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_end_customers', to='bills.package'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='bill_record',
            field=models.ForeignKey(blank=True, help_text='Bandwidth/Reseller bill record this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.billrecord'),
        ),
    ]
