# Generated by Django 5.2.8 on 2025-11-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nttn_cap', models.CharField(blank=True, max_length=100)),
                ('nttn_com', models.CharField(blank=True, max_length=100)),
                ('active_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('iig_qt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iig_qt_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fna', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fna_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ggc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ggc_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cdn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cdn_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bdix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bdix_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('baishan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('baishan_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='customers.customer')),
            ],
            options={
                'db_table': 'bill_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
