# Generated by Django 5.2.8 on 2025-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_bill_created_by_remove_bill_customer_and_more'),
        ('customers', '0006_customer_customer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='bill_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated bill number: KTL-BL-{7 chars of customer name}-{DDMMYYYY}', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['bill_number'], name='bill_record_bill_nu_8dd773_idx'),
        ),
    ]
