# Generated by Django 5.2.8 on 2025-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_invoicemaster_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerentitlementdetails',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes (e.g., bandwidth type for BW customers)', null=True),
        ),
    ]
