# Generated by Django 5.2.8 on 2025-11-23 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='mac_bill',
            field=models.ForeignKey(blank=True, help_text='MAC bill this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.macbill'),
        ),
        migrations.AddField(
            model_name='pricingperiod',
            name='bill_record',
            field=models.ForeignKey(help_text='The bill record this pricing period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_periods', to='bills.billrecord'),
        ),
        migrations.AddField(
            model_name='dailybillamount',
            name='pricing_period',
            field=models.ForeignKey(blank=True, help_text='The pricing period used for this day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_amounts', to='bills.pricingperiod'),
        ),
        migrations.AddField(
            model_name='sohobill',
            name='package',
            field=models.ForeignKey(help_text='Package at time of billing', limit_choices_to={'type': 'SOHO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soho_bills', to='bills.package'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='soho_bill',
            field=models.ForeignKey(blank=True, help_text='SOHO bill this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.sohobill'),
        ),
        migrations.AddField(
            model_name='sohocustomer',
            name='package',
            field=models.ForeignKey(help_text='SOHO package assigned to this customer', limit_choices_to={'type': 'SOHO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soho_customers', to='bills.package'),
        ),
        migrations.AddField(
            model_name='sohobill',
            name='soho_customer',
            field=models.ForeignKey(help_text='SOHO customer this bill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bills.sohocustomer'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['bill_number'], name='bill_record_bill_nu_8dd773_idx'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['customer', 'status'], name='bill_record_custome_7c0038_idx'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['customer'], name='bill_record_custome_adeaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='macbill',
            index=models.Index(fields=['mac_partner', 'bill_date'], name='mac_bills_mac_par_71a7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='macbill',
            index=models.Index(fields=['status'], name='mac_bills_status_914f53_idx'),
        ),
        migrations.AddIndex(
            model_name='macbill',
            index=models.Index(fields=['bill_date'], name='mac_bills_bill_da_b93615_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['mac_partner', 'status'], name='mac_end_cus_mac_par_499eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['activation_date'], name='mac_end_cus_activat_4af87e_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['status'], name='mac_end_cus_status_d92c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['mac_end_customer_number'], name='mac_end_cus_mac_end_6864c2_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingperiod',
            index=models.Index(fields=['bill_record', 'start_day'], name='bill_pricin_bill_re_bdf03c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_day__gte', 1), ('start_day__lte', 31)), name='valid_start_day'),
        ),
        migrations.AddConstraint(
            model_name='pricingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_day__gte', 1), ('end_day__lte', 31)), name='valid_end_day'),
        ),
        migrations.AddIndex(
            model_name='dailybillamount',
            index=models.Index(fields=['bill_record', 'date'], name='bill_daily__bill_re_de6889_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybillamount',
            index=models.Index(fields=['date'], name='bill_daily__date_9045ac_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybillamount',
            index=models.Index(fields=['bill_record', 'day_number'], name='bill_daily__bill_re_0c36c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailybillamount',
            unique_together={('bill_record', 'date')},
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_date'], name='payment_rec_payment_5f9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_type'], name='payment_rec_payment_1ac056_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['mac_bill'], name='payment_rec_mac_bil_e4e5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['soho_bill'], name='payment_rec_soho_bi_cd6171_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['bill_record'], name='payment_rec_bill_re_4d4180_idx'),
        ),
        migrations.AddIndex(
            model_name='sohocustomer',
            index=models.Index(fields=['status'], name='soho_custom_status_d47e52_idx'),
        ),
        migrations.AddIndex(
            model_name='sohocustomer',
            index=models.Index(fields=['activation_date'], name='soho_custom_activat_f8e642_idx'),
        ),
        migrations.AddIndex(
            model_name='sohocustomer',
            index=models.Index(fields=['soho_customer_number'], name='soho_custom_soho_cu_2c9505_idx'),
        ),
        migrations.AddIndex(
            model_name='sohobill',
            index=models.Index(fields=['soho_customer', 'bill_date'], name='soho_bills_soho_cu_9ef951_idx'),
        ),
        migrations.AddIndex(
            model_name='sohobill',
            index=models.Index(fields=['status'], name='soho_bills_status_27f31d_idx'),
        ),
        migrations.AddIndex(
            model_name='sohobill',
            index=models.Index(fields=['bill_date'], name='soho_bills_bill_da_41e86f_idx'),
        ),
    ]
