# Generated by Django 5.2.8 on 2025-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_customerentitlementdetails_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerentitlementmaster',
            name='link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerentitlementmaster',
            name='nttn_uses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
