# Generated by Django 5.2.8 on 2025-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_billrecord_bill_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrecord',
            name='bill_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated bill number: KTL-BL-{5 chars customer name}-{bill id}-{DDMMYYYY}', max_length=50, null=True, unique=True),
        ),
    ]
