# Generated by Django 5.2.8 on 2025-11-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_billrecord_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.IntegerField(help_text='Start day of the period (1-31)')),
                ('end_day', models.IntegerField(help_text='End day of the period (1-31)')),
                ('iig_qt', models.DecimalField(decimal_places=2, default=0, help_text='IIG QT usage/quantity for this period', max_digits=10)),
                ('fna', models.DecimalField(decimal_places=2, default=0, help_text='FNA usage/quantity for this period', max_digits=10)),
                ('ggc', models.DecimalField(decimal_places=2, default=0, help_text='GGC usage/quantity for this period', max_digits=10)),
                ('cdn', models.DecimalField(decimal_places=2, default=0, help_text='CDN usage/quantity for this period', max_digits=10)),
                ('bdix', models.DecimalField(decimal_places=2, default=0, help_text='BDIX usage/quantity for this period', max_digits=10)),
                ('baishan', models.DecimalField(decimal_places=2, default=0, help_text='Baishan usage/quantity for this period', max_digits=10)),
                ('iig_qt_price', models.DecimalField(decimal_places=2, default=0, help_text='IIG QT price per unit for this period', max_digits=10)),
                ('fna_price', models.DecimalField(decimal_places=2, default=0, help_text='FNA price per unit for this period', max_digits=10)),
                ('ggc_price', models.DecimalField(decimal_places=2, default=0, help_text='GGC price per unit for this period', max_digits=10)),
                ('cdn_price', models.DecimalField(decimal_places=2, default=0, help_text='CDN price per unit for this period', max_digits=10)),
                ('bdix_price', models.DecimalField(decimal_places=2, default=0, help_text='BDIX price per unit for this period', max_digits=10)),
                ('baishan_price', models.DecimalField(decimal_places=2, default=0, help_text='Baishan price per unit for this period', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Notes about this pricing period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_record', models.ForeignKey(help_text='The bill record this pricing period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_periods', to='bills.billrecord')),
            ],
            options={
                'db_table': 'bill_pricing_periods',
                'ordering': ['bill_record', 'start_day'],
            },
        ),
        migrations.CreateModel(
            name='DailyBillAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The specific date for this daily amount')),
                ('day_number', models.IntegerField(help_text='Day number within the billing period (1-31)')),
                ('iig_qt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fna', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ggc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cdn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bdix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('baishan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total bill amount for this specific day', max_digits=15)),
                ('service_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown of daily amount by service component')),
                ('is_calculated', models.BooleanField(default=True, help_text='Whether this amount was auto-calculated or manually entered')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_record', models.ForeignKey(help_text='The bill record this daily amount belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_amounts', to='bills.billrecord')),
                ('pricing_period', models.ForeignKey(blank=True, help_text='The pricing period used for this day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_amounts', to='bills.pricingperiod')),
            ],
            options={
                'db_table': 'bill_daily_amounts',
                'ordering': ['bill_record', 'date'],
            },
        ),
        migrations.AddIndex(
            model_name='pricingperiod',
            index=models.Index(fields=['bill_record', 'start_day'], name='bill_pricin_bill_re_bdf03c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_day__gte', 1), ('start_day__lte', 31)), name='valid_start_day'),
        ),
        migrations.AddConstraint(
            model_name='pricingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_day__gte', 1), ('end_day__lte', 31)), name='valid_end_day'),
        ),
        migrations.AddIndex(
            model_name='dailybillamount',
            index=models.Index(fields=['bill_record', 'date'], name='bill_daily__bill_re_de6889_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybillamount',
            index=models.Index(fields=['date'], name='bill_daily__date_9045ac_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybillamount',
            index=models.Index(fields=['bill_record', 'day_number'], name='bill_daily__bill_re_0c36c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailybillamount',
            unique_together={('bill_record', 'date')},
        ),
    ]
