# Generated by Django 5.2.8 on 2025-11-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_pricingperiod_dailybillamount_and_more'),
        ('customers', '0008_customer_customer_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='customer_type',
            field=models.CharField(choices=[('Bandwidth', 'Bandwidth/Reseller Customer'), ('MAC', 'MAC Partner/Channel Partner/Franchise'), ('SOHO', 'SOHO/Home Customer')], db_index=True, default='Bandwidth', help_text='Type of customer this bill is for', max_length=20),
        ),
        migrations.AddField(
            model_name='billrecord',
            name='last_payment_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of last payment received', null=True),
        ),
        migrations.AddField(
            model_name='billrecord',
            name='last_payment_mode',
            field=models.CharField(blank=True, help_text='Payment mode of last payment (Cash, Bank Transfer, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='billrecord',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Bandwidth/Reseller customer (if customer_type is Bandwidth)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='MACPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_cust_name', models.CharField(help_text='MAC partner name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('mac_partner_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated MAC partner number: KTL-MAC-{8 chars partner name}-{partner id}', max_length=50, null=True, unique=True)),
                ('percentage_share', models.DecimalField(decimal_places=2, default=0, help_text='Revenue share percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mac_partners',
                'ordering': ['mac_cust_name'],
                'indexes': [models.Index(fields=['mac_cust_name'], name='mac_partner_mac_cus_bb6c31_idx'), models.Index(fields=['is_active'], name='mac_partner_is_acti_3a80b2_idx'), models.Index(fields=['mac_partner_number'], name='mac_partner_mac_par_6c9b03_idx')],
            },
        ),
        migrations.CreateModel(
            name='MACBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(help_text='Billing date')),
                ('total_client', models.IntegerField(default=0, help_text='Total active clients at billing date (auto-calculated)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from all active end-customers', max_digits=15)),
                ('percentage_share', models.DecimalField(decimal_places=2, default=0, help_text='Revenue share percentage applied', max_digits=5)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Commission amount (auto-calculated: total_revenue * percentage_share / 100)', max_digits=15)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, help_text='Total bill after commission (total_revenue - commission)', max_digits=15)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, help_text='Total amount received', max_digits=15)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, help_text='Total due amount (total_bill - total_received)', max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], db_index=True, default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_partner', models.ForeignKey(help_text='MAC partner this bill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bills.macpartner')),
            ],
            options={
                'db_table': 'mac_bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='billrecord',
            name='mac_partner',
            field=models.ForeignKey(blank=True, help_text='MAC Partner (if customer_type is MAC)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='bills.macpartner'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package name', max_length=255)),
                ('mbps', models.DecimalField(decimal_places=2, help_text='Speed in Mbps', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Base package price', max_digits=12)),
                ('type', models.CharField(choices=[('MAC', 'MAC Package'), ('SOHO', 'SOHO Package')], db_index=True, help_text='Package type: MAC or SOHO', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='packages_type_e704ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='MACEndCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='End customer name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('mac_end_customer_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated MAC end customer number: KTL-MACEC-{8 chars customer name}-{customer id}', max_length=50, null=True, unique=True)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom rate for this customer (if different from package rate)', max_digits=12, null=True)),
                ('activation_date', models.DateField(db_index=True, help_text='Date when customer became active')),
                ('bill_date', models.DateField(blank=True, db_index=True, help_text='Individual bill date for this customer (if different from MAC partner bill date)', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], db_index=True, default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_partner', models.ForeignKey(help_text='MAC partner this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='end_customers', to='bills.macpartner')),
                ('package', models.ForeignKey(help_text='Package assigned to this customer', limit_choices_to={'type': 'MAC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_end_customers', to='bills.package')),
            ],
            options={
                'db_table': 'mac_end_customers',
                'ordering': ['mac_partner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SOHOBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(help_text='Billing date')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate charged for this bill', max_digits=12)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, help_text='Total bill amount', max_digits=15)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, help_text='Total amount received', max_digits=15)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, help_text='Total due amount (total_bill - total_received)', max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], db_index=True, default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(help_text='Package at time of billing', limit_choices_to={'type': 'SOHO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soho_bills', to='bills.package')),
            ],
            options={
                'db_table': 'soho_bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_index=True, help_text='Date when payment was received')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=15)),
                ('payment_type', models.CharField(choices=[('MAC', 'MAC Bill Payment'), ('SOHO', 'SOHO Bill Payment'), ('Bandwidth', 'Bandwidth/Reseller Bill Payment'), ('Other', 'Other Payment')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Check', 'Check'), ('Mobile Banking', 'Mobile Banking'), ('Other', 'Other')], default='Bank Transfer', max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference/transaction ID', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_record', models.ForeignKey(blank=True, help_text='Bandwidth/Reseller bill record this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.billrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
                ('mac_bill', models.ForeignKey(blank=True, help_text='MAC bill this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.macbill')),
                ('soho_bill', models.ForeignKey(blank=True, help_text='SOHO bill this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.sohobill')),
            ],
            options={
                'db_table': 'payment_records',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOHOCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(help_text='Customer name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('soho_customer_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated SOHO customer number: KTL-SOHO-{8 chars customer name}-{customer id}', max_length=50, null=True, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Package rate (can override package default rate)', max_digits=12)),
                ('activation_date', models.DateField(help_text='Date when customer became active')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], db_index=True, default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(help_text='SOHO package assigned to this customer', limit_choices_to={'type': 'SOHO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soho_customers', to='bills.package')),
            ],
            options={
                'db_table': 'soho_customers',
                'ordering': ['cust_name'],
            },
        ),
        migrations.AddField(
            model_name='sohobill',
            name='soho_customer',
            field=models.ForeignKey(help_text='SOHO customer this bill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bills.sohocustomer'),
        ),
        migrations.AddField(
            model_name='billrecord',
            name='soho_customer',
            field=models.ForeignKey(blank=True, help_text='SOHO Customer (if customer_type is SOHO)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='bills.sohocustomer'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['customer_type', 'status'], name='bill_record_custome_281909_idx'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['customer'], name='bill_record_custome_adeaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['mac_partner'], name='bill_record_mac_par_f4e911_idx'),
        ),
        migrations.AddIndex(
            model_name='billrecord',
            index=models.Index(fields=['soho_customer'], name='bill_record_soho_cu_82e846_idx'),
        ),
        migrations.AddIndex(
            model_name='macbill',
            index=models.Index(fields=['mac_partner', 'bill_date'], name='mac_bills_mac_par_71a7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='macbill',
            index=models.Index(fields=['status'], name='mac_bills_status_914f53_idx'),
        ),
        migrations.AddIndex(
            model_name='macbill',
            index=models.Index(fields=['bill_date'], name='mac_bills_bill_da_b93615_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['mac_partner', 'status'], name='mac_end_cus_mac_par_499eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['activation_date'], name='mac_end_cus_activat_4af87e_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['status'], name='mac_end_cus_status_d92c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='macendcustomer',
            index=models.Index(fields=['mac_end_customer_number'], name='mac_end_cus_mac_end_6864c2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_date'], name='payment_rec_payment_5f9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_type'], name='payment_rec_payment_1ac056_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['mac_bill'], name='payment_rec_mac_bil_e4e5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['soho_bill'], name='payment_rec_soho_bi_cd6171_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['bill_record'], name='payment_rec_bill_re_4d4180_idx'),
        ),
        migrations.AddIndex(
            model_name='sohocustomer',
            index=models.Index(fields=['status'], name='soho_custom_status_d47e52_idx'),
        ),
        migrations.AddIndex(
            model_name='sohocustomer',
            index=models.Index(fields=['activation_date'], name='soho_custom_activat_f8e642_idx'),
        ),
        migrations.AddIndex(
            model_name='sohocustomer',
            index=models.Index(fields=['soho_customer_number'], name='soho_custom_soho_cu_2c9505_idx'),
        ),
        migrations.AddIndex(
            model_name='sohobill',
            index=models.Index(fields=['soho_customer', 'bill_date'], name='soho_bills_soho_cu_9ef951_idx'),
        ),
        migrations.AddIndex(
            model_name='sohobill',
            index=models.Index(fields=['status'], name='soho_bills_status_27f31d_idx'),
        ),
        migrations.AddIndex(
            model_name='sohobill',
            index=models.Index(fields=['bill_date'], name='soho_bills_bill_da_41e86f_idx'),
        ),
    ]
