# Generated by Django 5.2.8 on 2025-11-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=1, help_text='Serial number in invoice table')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text="Full description with date range (e.g., 'IT Supports (1st June to 30th June-2025)')")),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_unit', models.CharField(blank=True, help_text="Unit for quantity (empty for ITS, 'Mbps' for INT)", max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Unit price (may be 0 or empty)', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Line amount (may be empty, calculated)', max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='Total Amount (BDT) - required', max_digits=15)),
                ('service_type', models.CharField(blank=True, help_text='Service type: ipt, fna, ggc, cdn, nix, baishan', max_length=50)),
                ('date_from', models.DateField(blank=True, help_text='Service start date for description', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Service end date for description', null=True)),
            ],
            options={
                'db_table': 'sales_invoice_items',
                'ordering': ['serial_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Format: KTL MM YYYY/XX', max_length=50, unique=True)),
                ('invoice_format', models.CharField(choices=[('ITS', 'ITS'), ('INT', 'INT')], default='ITS', max_length=10)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='VAT amount (usually 0 for ITS, calculated for INT)', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_in_words', models.TextField(blank=True, help_text="Total amount in words (e.g., 'Two Lac Sixty-Six Thousand Fifty-Seven Taka Only.')")),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the invoice')),
                ('terms', models.TextField(blank=True, help_text='Payment terms and conditions')),
                ('attention', models.CharField(blank=True, help_text='Attention line (defaults to customer name)', max_length=255)),
                ('payment_mode', models.CharField(default='Kloud Technologies Limited', max_length=255)),
                ('bank_name', models.CharField(default='National Credit and Commerce Bank PLC. (NCC)', max_length=255)),
                ('account_number', models.CharField(default='0050-0210013920', max_length=50)),
                ('branch_name', models.CharField(default='Banani', max_length=255)),
                ('routing_number', models.CharField(default='160260430', max_length=50)),
                ('swift_code', models.CharField(default='NCCLBDDHBAB', max_length=50)),
                ('bkash_number', models.CharField(default='01313752577', max_length=50)),
                ('manager_name', models.CharField(default='Biswajit Kumar Ghosh', max_length=255)),
                ('manager_designation', models.CharField(default='Manager (Finance & Accounts)', max_length=255)),
                ('manager_email', models.CharField(default='biswajit.kumar@kloud.com.bd', max_length=255)),
                ('manager_phone', models.CharField(default='01727-051616', max_length=50)),
                ('company_name_footer', models.CharField(default='Kloud Technologies Limited', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bill_record', models.OneToOneField(help_text='The bill record this invoice is based on', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bills.billrecord')),
            ],
            options={
                'db_table': 'sales_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
