# Generated by Django 5.2.8 on 2025-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['serial_number', 'id']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(default='0050-0210013920', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_in_words',
            field=models.TextField(blank=True, help_text="Total amount in words (e.g., 'Two Lac Sixty-Six Thousand Fifty-Seven Taka Only.')"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='attention',
            field=models.CharField(blank=True, help_text='Attention line (defaults to customer name)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(default='National Credit and Commerce Bank PLC. (NCC)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bkash_number',
            field=models.CharField(default='01313752577', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch_name',
            field=models.CharField(default='Banani', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_name_footer',
            field=models.CharField(default='Kloud Technologies Limited', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manager_designation',
            field=models.CharField(default='Manager (Finance & Accounts)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manager_email',
            field=models.CharField(default='biswajit.kumar@kloud.com.bd', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manager_name',
            field=models.CharField(default='Biswajit Kumar Ghosh', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manager_phone',
            field=models.CharField(default='01727-051616', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(default='Kloud Technologies Limited', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='routing_number',
            field=models.CharField(default='160260430', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='swift_code',
            field=models.CharField(default='NCCLBDDHBAB', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Line amount (may be empty, calculated)', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date_from',
            field=models.DateField(blank=True, help_text='Service start date for description', null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date_to',
            field=models.DateField(blank=True, help_text='Service end date for description', null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='quantity_unit',
            field=models.CharField(blank=True, help_text="Unit for quantity (empty for ITS, 'Mbps' for INT)", max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='serial_number',
            field=models.IntegerField(default=1, help_text='Serial number in invoice table'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, help_text='Format: KTL MM YYYY/XX', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT amount (usually 0 for ITS, calculated for INT)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True, help_text="Full description with date range (e.g., 'IT Supports (1st June to 30th June-2025)')"),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Amount (BDT) - required', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit price (may be 0 or empty)', max_digits=10),
        ),
    ]
