# Generated by Django 5.2.8 on 2025-11-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('bw', 'Bandwidth'), ('channel_partner', 'Channel Partner'), ('soho', 'SOHO/Home')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'package_master',
                'ordering': ['package_name'],
            },
        ),
        migrations.CreateModel(
            name='PackagePricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Only for home packages', max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('val_start_at', models.DateField(help_text='Validity start date')),
                ('val_end_at', models.DateField(help_text='Validity end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_master_id', models.ForeignKey(db_column='package_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='package.packagemaster')),
            ],
            options={
                'db_table': 'package_pricing',
                'ordering': ['-val_start_at'],
            },
        ),
    ]
