# Generated by Django 5.2.8 on 2025-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepricing',
            name='mbps',
            field=models.IntegerField(blank=True, help_text='Bandwidth in Mbps', null=True),
        ),
    ]
