# Generated by Django 5.2.8 on 2025-11-27 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(help_text='e.g., Credit Card, Bank Transfer, Cash', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('customer_entitlement_master_id', models.ForeignKey(db_column='customer_entitlement_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.customerentitlementmaster')),
                ('invoice_master_id', models.ForeignKey(db_column='invoice_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.invoicemaster')),
                ('received_by', models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_master',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_details', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_details', to=settings.AUTH_USER_MODEL)),
                ('payment_master_id', models.ForeignKey(db_column='payment_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payment.paymentmaster')),
            ],
            options={
                'db_table': 'payment_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
