# Generated by Django 5.2.8 on 2025-11-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='menu_items', to='authentication.role')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authentication.menuitem')),
                ('required_permissions', models.ManyToManyField(blank=True, related_name='menu_items', to='authentication.permission')),
            ],
            options={
                'db_table': 'auth_menu_items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
