# Generated by Django 5.2.8 on 2025-11-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('users', 'Users'), ('customers', 'Customers'), ('prospects', 'Prospects'), ('bills', 'Bills'), ('dashboard', 'Dashboard'), ('reports', 'Reports'), ('settings', 'Settings'), ('logs', 'Logs'), ('role', 'Roles')], max_length=50),
        ),
    ]
